// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MuxiKeStack/be-tag/grpc"
	"github.com/MuxiKeStack/be-tag/ioc"
	"github.com/MuxiKeStack/be-tag/pkg/grpcx"
	"github.com/MuxiKeStack/be-tag/repository"
	"github.com/MuxiKeStack/be-tag/repository/dao"
	"github.com/MuxiKeStack/be-tag/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	tagDAO := dao.NewGORMTagDAO(db)
	tagRepository := repository.NewTagRepository(tagDAO)
	generalTagService := service.NewGeneralTagService(tagRepository)
	tagServiceServer := grpc.NewTagServiceServer(generalTagService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(tagServiceServer, client, logger)
	return server
}
