mysql:
  dsn: "root:root@tcp(localhost:3306)/kstack?multiStatements=true&interpolateParams=true"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    name: "tag"
    weight: 100
    addr: ":8096"
    etcdTTL: 60